# Generated by Django 5.0.7 on 2025-08-28 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyCampaign',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('created_at', models.CharField(blank=True, max_length=40, null=True)),
                ('message_template', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'survey_campaigns',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SurveyInvite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('sent_at', models.CharField(blank=True, max_length=40, null=True)),
                ('responded_at', models.CharField(blank=True, max_length=40, null=True)),
                ('reminders_sent', models.IntegerField(default=0)),
                ('last_reminder_at', models.CharField(blank=True, max_length=40, null=True)),
                ('available_all', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'survey_invites',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('kitchen_eligible', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'members',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MemberPref',
            fields=[
                ('member', models.OneToOneField(db_column='member_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.member')),
                ('language', models.CharField(choices=[('pt', 'Português'), ('es', 'Español')], default='pt', max_length=2)),
            ],
            options={
                'db_table': 'member_prefs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Unavailability',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=10)),
                ('role', models.CharField(blank=True, max_length=20, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('member', models.ForeignKey(db_column='member_id', on_delete=django.db.models.deletion.DO_NOTHING, to='core.member')),
            ],
            options={
                'db_table': 'unavailability',
                'managed': True,
            },
        ),
    ]
